# Generated by Django 4.0.7 on 2022-10-20 18:41

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields
import root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(default='Nairobi', max_length=50)),
                ('town', models.CharField(default='Juja', max_length=50)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('twitter_handle', models.URLField()),
                ('facebook', models.URLField()),
                ('linked_in', models.URLField()),
                ('instagram', models.URLField()),
                ('logo', django_resized.forms.ResizedImageField(crop=None, default='uploads\\logo\\default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to=root.models.logo_filename)),
            ],
        ),
        migrations.CreateModel(
            name='FrontDisplayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Sliders', 'Sliders'), ('Brands', 'Brands')], db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='uploads\\display\\default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[150, 150], upload_to=root.models.content_file_name)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='root.frontdisplaycategory')),
            ],
        ),
    ]
