# Generated by Django 4.0.8 on 2022-12-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_contactinfo_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_subscribed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ('-created',),
            },
        ),
    ]
