# Generated by Django 4.0.8 on 2023-01-03 06:31

from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_subsubscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='town',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='street',
            field=models.CharField(default='Moi Avenue', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='logo',
            field=models.ImageField(upload_to=root.models.logo_filename),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter_handle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='zip_code',
            field=models.CharField(default='7800-896', max_length=50),
            preserve_default=False,
        ),
    ]
