# Generated by Django 4.0.8 on 2023-01-03 06:47

from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_contactinfo_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontdisplay',
            name='image',
            field=models.ImageField(upload_to=root.models.content_file_name),
        ),
    ]
